# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model import Model


class Ui_MainWindow(object):
    def __init__( self ):
        #Initialize the super class
        super().__init__()
        self.model = Model(self)

    def setupUi(self, MainWindow):
        # This function is auto generated by Qt Designer
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 481, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.sourceFileLine = QtWidgets.QLineEdit(self.frame)
        self.sourceFileLine.setGeometry(QtCore.QRect(70, 20, 301, 20))
        self.sourceFileLine.setObjectName("sourceFileLine")
        self.button1 = QtWidgets.QPushButton(self.frame)
        self.button1.setGeometry(QtCore.QRect(390, 20, 75, 23))
        self.button1.setObjectName("button1")
        self.button1.clicked.connect(lambda: self.browseButtonClicked(1))   # bind click function
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 481, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 54, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.targetFileLine = QtWidgets.QLineEdit(self.frame_2)
        self.targetFileLine.setGeometry(QtCore.QRect(70, 20, 301, 20))
        self.targetFileLine.setObjectName("targetFileLine")
        self.button2 = QtWidgets.QPushButton(self.frame_2)
        self.button2.setGeometry(QtCore.QRect(390, 20, 75, 23))
        self.button2.setObjectName("button2")
        self.button2.clicked.connect(lambda: self.browseButtonClicked(2))   # bind click function
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 110, 281, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.keyColumnLine = QtWidgets.QLineEdit(self.frame_3)
        self.keyColumnLine.setGeometry(QtCore.QRect(140, 20, 111, 20))
        self.keyColumnLine.setObjectName("keyColumnLine")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(340, 120, 131, 41))
        self.button3.setObjectName("button3")
        self.button3.clicked.connect(self.button3Clicked)   # bind click function
        self.debugTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.debugTextBrowser.setGeometry(QtCore.QRect(30, 170, 431, 171))
        self.debugTextBrowser.setObjectName("debugTextBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Source"))
        self.button1.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Target"))
        self.button2.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Key Column Name:"))
        self.button3.setText(_translate("MainWindow", "Start"))
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Excel Processor")) # Window Title
    
    def debugPrint( self, msgType, msg ):   #1:info  #2: warning  #3: error
        '''Print the message in the text edit at the bottom of the
        horizontal splitter.
        '''
        if msgType == 1:
            self.debugTextBrowser.append( '[INFO] ' + msg )
        elif msgType == 2:
            self.debugTextBrowser.append( '[WARNING] ' + msg )
        else:
            self.debugTextBrowser.append( '[ERROR] ' + msg )
    
    def browseButtonClicked(self, type):
        fileName = self.browseFile()
        if fileName:
            if type == 1:
                self.debugPrint( 1, "Set source file name: " + fileName )
                self.sourceFileLine.setText(fileName)
            else:
                self.debugPrint( 1, "Set target file name: " + fileName )
                self.targetFileLine.setText(fileName)
        else:
            self.debugPrint( 2, "Failed to find this file" )

    
    def browseFile(self):
        # 打开文件目录窗口，选取文件
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
                        None,
                        "QFileDialog.getOpenFileName()",
                        "",
                        "WPS Excel文档 (*.xls);;Office Excel文档 (*.xlsx)",
                        options=options)
        return fileName
    
    def button3Clicked(self):
        # Check if input is empty
        source_fn = self.sourceFileLine.text()
        if not source_fn:
            self.debugPrint( 2, "Source file is empty" )
            return

        target_fn = self.targetFileLine.text()
        if not target_fn:
            self.debugPrint( 2, "Target file is empty" )
            return

        keyColumn = self.keyColumnLine.text()
        if not keyColumn:
            self.debugPrint( 2, "key Column Name is empty" )
            return

        self.model.process(source_fn, target_fn, keyColumn)  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
