# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/07.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AboutDialog(object):
    def setupUi(self, Dialog, assetPath):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 218)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(assetPath + 'icon.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, lan):
        if lan == 1:
            self.Dialog.setWindowTitle("关于")
            self.label.setText("<html><head/><body><p><span style=\" font-weight:600;\">Excel 自动处理工具</span></p></body></html>")
            self.label_4.setText("作者: Aaron Leo")
            self.label_3.setText("联系方式:aaronxyliu@qq.com")
            self.label_2.setText("<html><head/><body><p><a href=\"https://github.com/NJUaaron/ExcelAutoProcess\"><span style=\" color:#d4466a;\">访问软件的 Github 主页</span></a></p></body></html>")
        else:
            self.Dialog.setWindowTitle("About")
            self.label.setText("<html><head/><body><p><span style=\" font-weight:600;\">Excel Auto Processor</span></p></body></html>")
            self.label_4.setText("Author: Aaron Leo")
            self.label_3.setText("Contact:aaronxyliu@qq.com")
            self.label_2.setText("<html><head/><body><p><a href=\"https://github.com/NJUaaron/ExcelAutoProcess\"><span style=\" color:#d4466a;\">Visit on Github webpage!!</span></a></p></body></html>")


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = AboutDialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
