# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/05.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LanDialog(object):
    # Language select dialog
    def __init__(self, viewInstance, aboutDialogInstance):
        self.view = viewInstance  # View instance
        self.aboutDialog = aboutDialogInstance  # About dialog instance
        self.Dialog = None

    def setupUi(self, Dialog, assetPath):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(288, 282)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(assetPath + 'icon.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(100, 50, 100, 100)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 20))
        self.label.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)

        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.toggled.connect(self.btnState)   # bind

        self.verticalLayout.addWidget(self.radioButton_2)

        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")

        self.verticalLayout.addWidget(self.radioButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    
    def btnState(self):
        # Toggle button
        if self.radioButton_2.isChecked()==True:
            # change to English
            self.retranslateUi(2)
            self.view.retranslateUi(2)
            self.aboutDialog.retranslateUi(2)
        else:
            # change to Chinese
            self.retranslateUi(1)
            self.view.retranslateUi(1)
            self.aboutDialog.retranslateUi(1)

    def retranslateUi(self, lan):
        if (lan == 1):
            self.Dialog.setWindowTitle("语言")
            self.label.setText("语言")
            self.radioButton_2.setText("英语")
            self.radioButton.setText("中文")
        else:
            _translate = QtCore.QCoreApplication.translate
            self.Dialog.setWindowTitle(_translate("Dialog", "Language"))
            self.label.setText(_translate("Dialog", "Language"))
            self.radioButton_2.setText(_translate("Dialog", "English"))
            self.radioButton.setText(_translate("Dialog", "Chinese"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = LanDialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
